#!/bin/bash

# Set up config files

######################
# VIM
######################
rm -f ~/.vimrc
ln -s `pwd`/vim/vimrc ~/.vimrc
# if OSX add .xvimrc for XCode.
if [[ `uname` == 'Darwin' ]]; then
    rm -f ~/.xvimrc
    ln -s `pwd`/vim/vimrc ~/.xvimrc
fi
if [ "`pwd`/vim/vim" != "`readlink ~/.vim`" ] || [ "$1" = "-f" ]; then
    rm -r ~/.vim
    ln -s `pwd`/vim/vim ~/.vim
fi

#rm -rf vim/bundle
mkdir -p vim/vim/bundle
pushd vim/vim/bundle/

# rust.vim
# git -C rust.vim pull || git clone --depth=1 https://github.com/rust-lang/rust.vim.git
# Powershell
# git -C vim-ps1 pull || git clone https://github.com/PProvost/vim-ps1.git

popd

######################
# Neo Vim
######################
# Ensure required directories exist
mkdir -p ~/.config/nvim
mkdir -p ~/.config/nvim/spell

# Set up symlinked ftplugin directory
rm -r ~/.config/nvim/ftplugin

# Clean up existing files that will be symlinked.
rm -f ~/.config/nvim/init.vim
rm -f ~/.config/nvim/spell/en.utf-8.add

# Symlink the files
ln -s `pwd`/nvim/init.vim ~/.config/nvim/init.vim
ln -s `pwd`/nvim/spell/en.utf-8.add ~/.config/nvim/spell/en.utf-8.add

# Symlink directories
ln -s `pwd`/nvim/ftplugin ~/.config/nvim/

######################
# BASH
######################
rm -f ~/.bashrc
ln -s `pwd`/bashrc ~/.bashrc

######################
# TMUX
######################
rm -f ~/.tmux.conf
ln -s `pwd`/tmux.conf ~/.tmux.conf

######################
# GIT
######################
rm -f ~/.gitconfig
ln -s `pwd`/gitconfig ~/.gitconfig

######################
# XRESOURCES
######################
rm -f ~/.Xresources
ln -s `pwd`/Xresources ~/.Xresources
