#!/bin/bash

# Set up config files

# VIM
rm -f ~/.vimrc
ln -s `pwd`/vimrc ~/.vimrc
# if OSX add .xvimrc for XCode.
if [[ `uname` == 'Darwin' ]]; then
    rm -f ~/.xvimrc
    ln -s `pwd`/vimrc ~/.xvimrc
fi
if [ "`pwd`/vim" != "`readlink ~/.vim`" ] || [ "$1" = "-f" ]; then
    rm -r ~/.vim
    ln -s `pwd`/vim ~/.vim
    rm -rf vim/bundle
    mkdir -p vim/bundle
    cd vim/bundle/
    # NERDTree
    git clone http://github.com/scrooloose/nerdtree.git
    # vim-go
    git clone http://github.com/fatih/vim-go.git
    # rust.vim
    git clone --depth=1 https://github.com/rust-lang/rust.vim.git
    cd ../../
fi

# BASH
rm -f ~/.bashrc
ln -s `pwd`/bashrc ~/.bashrc

# TMUX
rm -f ~/.tmux.conf
ln -s `pwd`/tmux.conf ~/.tmux.conf

# GIT
rm -f ~/.gitconfig
ln -s `pwd`/gitconfig ~/.gitconfig

# XRESOURCES
rm -f ~/.Xresources
ln -s `pwd`/Xresources ~/.Xresources
